### PR TITLE
Ubuntu 18.04 LTS

### LINKED ISSUE #21: Ubuntu 18.04 LTS
Ubuntu 18.04 LTS is out and we should update: http://releases.ubuntu.com/18.04/

### PR DESCRIPTION
**Pull request by hjacobs**
Update to latest Ubuntu 18.04 LTS.

Fixes #21.

### CODE REVIEW

**Comment by harti2006** [comment]
How likely will this break our docker images that always use `latest` version of this as their base?

**Comment by hjacobs** [comment]
@harti2006 I don't know, I think OpenJDK 8 and Python should work totally fine, but (as always) there might be some minor details and corner cases which would break something.

I would recommend discussing this (internally), making everybody aware of the coming update and merge it (without introducing a different image name).

**Comment by hjacobs** [comment]
BTW: I updated all my personal devices (2x desktop, 1x laptop) to Xubuntu 18.04 LTS and don't see any problems.

**Comment by jmcs** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

**Pull request merged**
